# **Experiment Notebook**

<hr>

## A. Project

In [ ]:
student_name = 'Sonal Rao'

In [ ]:
student_id = '25533441'

In [ ]:
experiment_id = '0'

In [ ]:
business_objective = '<fill_this>'

<hr>

## B. Experiment Description

In [ ]:
experiment_hypothesis = 'There is no hypothesis to test. This is used for data exploration and analysis and required data preparation for the upcoming experiments.'

In [ ]:
experiment_expectations = 'The goal is to assess the baseline performance for this project and fix critical data quality issues impacting models.'

<hr>

## C. Data Understanding

In [ ]:
data_understanding_executive_summary = '<fill_this>'

### C.0 Import Packages

In [2]:
# Pandas for data handling
import pandas as pd

# Scikit Learn for ML training
import sklearn

# Altair for plotting
import altair as alt

# <fill_this>
import numpy as np

<hr>

### C.1   Load Datasets

In [4]:
# Load training data
# Do not change this code

training_df = pd.read_csv("salary_training.csv")

In [5]:
# Load validation data
# Do not change this code

validation_df = pd.read_csv("salary_validation.csv")

In [6]:
# Load testing data
# Do not change this code

testing_df = pd.read_csv("salary_testing.csv")

<hr>

### C.2 Explore Datasets

In [8]:
# <fill_this>

training_df.head()

,ID,Gender,DOB,10percentage,12graduation,12percentage,CollegeID,CollegeTier,Degree,Specialization,...,city,postcode,state_abbr,address,cc_number,cc_expiry,cc_security_code,company_name,company_suffix,user_agent
0,301647,m,1989-08-21,77.33,2007,85.17,9084,2,B.Tech/B.E.,electronics & telecommunications,...,New Nicoleborough,2223,NT,"9/48 Stephanie Crossway Ridge, New Nicoleborou...",5141731810295468,11/29,123,Hawkins Inc,LLC,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...
1,339001,f,1990-10-30,82.00,2008,75.00,4889,2,B.Tech/B.E.,biotechnology,...,Rossshire,2619,QLD,"Suite 618 65 Suzanne Underpass Circlet, Rosssh...",30024791814449,12/30,338,Ramirez-Strickland,Group,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...
2,1183070,m,1992-11-25,76.80,2010,87.70,5338,2,B.Tech/B.E.,information technology,...,Allenmouth,5622,WA,"Unit 58 195 David Basin River, Allenmouth WA,...",3507982022136239,04/28,842,"Morris, Velez and Duke",LLC,Mozilla/5.0 (Windows NT 5.2; fa-IR; rv:1.9.0.2...
3,794062,f,1993-03-15,57.00,2009,73.00,8346,2,B.Tech/B.E.,computer science & engineering,...,Morrisborough,2991,SA,"Level 5 385 Lisa Ramble Highroad, Morrisboroug...",6588817354931234,02/26,110,"Wilkins, Martinez and Harmon",and Sons,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...
4,1088206,m,1990-06-21,77.00,2008,75.00,13424,2,B.Tech/B.E.,electronics & telecommunications,...,Thompsonside,1375,QLD,"Flat 90 8 Peggy Rotary Place, Thompsonside QL...",2497754501717100,01/33,191,"Evans, Buckley and Gibson",Ltd,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9...

In [10]:
training_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1803 entries, 0 to 1802
Data columns (total 58 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     1803 non-null   int64
 1   Gender                 1803 non-null   object
 2   DOB                    1803 non-null   object
 3   10percentage           1803 non-null   float64
 4   12graduation           1803 non-null   int64
 5   12percentage           1803 non-null   float64
 6   CollegeID              1803 non-null   int64
 7   CollegeTier            1803 non-null   int64
 8   Degree                 1803 non-null   object
 9   Specialization         1803 non-null   object
 10  collegeGPA             1803 non-null   float64
 11  CollegeCityID          1803 non-null   int64
 12  CollegeCityTier        1803 non-null   int64
 13  GraduationYear         1803 non-null   int64
 14  English                1803 non-null   int64
 15  Logical                1803 non-null   int64
 16  Quant                  1803 non-null   int64
 17  Domain                 1803 non-null   float64
 18  ComputerProgramming    1803 non-null   int64
 19  ElectronicsAndSemicon  1803 non-null   int64
 20  ComputerScience        1803 non-null   int64
 21  MechanicalEngg         1803 non-null   int64
 22  ElectricalEngg         1803 non-null   int64
 23  TelecomEngg            1803 non-null   int64
 24  CivilEngg              1803 non-null   int64
 25  conscientiousness      1803 non-null   float64
 26  agreeableness          1803 non-null   float64
 27  extraversion           1803 non-null   float64
 28  nueroticism            1803 non-null   float64
 29  openess_to_experience  1803 non-null   float64
 30  Salary                 1803 non-null   float64
 31  profile                1803 non-null   object
 32  locale                 1803 non-null   object
 33  prefix                 1803 non-null   object
 34  first_name             1803 non-null   object
 35  last_name              1802 non-null   object
 36  full_name              1803 non-null   object
 37  gender                 1803 non-null   object
 38  dob                    1803 non-null   object
 39  birth_country          1803 non-null   object
 40  passport_number        1803 non-null   object
 41  passport_expiry        1803 non-null   object
 42  phone_number           1803 non-null   object
 43  email                  1803 non-null   object
 44  secondary_address      1803 non-null   object
 45  building_number        1803 non-null   int64
 46  street_name            1803 non-null   object
 47  street_suffix          1803 non-null   object
 48  city                   1803 non-null   object
 49  postcode               1803 non-null   int64
 50  state_abbr             1803 non-null   object
 51  address                1803 non-null   object
 52  cc_number              1803 non-null   int64
 53  cc_expiry              1803 non-null   object
 54  cc_security_code       1803 non-null   int64
 55  company_name           1803 non-null   object
 56  company_suffix         1803 non-null   object
 57  user_agent             1803 non-null   object
dtypes: float64(10), int64(21), object(27)
memory usage: 817.1+ KB

In [12]:
training_df.describe()

,ID,10percentage,12graduation,12percentage,CollegeID,CollegeTier,collegeGPA,CollegeCityID,CollegeCityTier,GraduationYear,...,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience,Salary,building_number,postcode,cc_number,cc_security_code
count,1.803000e+03,1803.000000,1803.000000,1803.000000,1803.000000,1803.000000,1803.000000,1803.000000,1803.000000,1803.000000,...,1803.000000,1803.000000,1803.000000,1803.000000,1803.000000,1803.000000,1803.000000,1803.000000,1.803000e+03,1803.000000
mean,7.217435e+05,78.283128,2008.357737,74.790372,5408.078203,1.929007,71.566312,5408.078203,0.305047,2011.709928,...,0.017035,0.172665,0.031829,-0.211467,-0.094496,85715.328342,187.722130,3176.981697,4.021968e+17,809.429285
std,3.495766e+05,9.752816,1.537590,10.844857,4844.573926,0.256884,7.947833,4844.573926,0.460555,47.418505,...,1.003619,0.911165,0.954190,1.003235,0.979686,2462.438200,283.021555,1881.770393,1.280105e+18,1365.229564
min,1.712600e+04,44.000000,2001.000000,40.000000,2.000000,1.000000,6.630000,2.000000,0.000000,0.000000,...,-3.353900,-4.283100,-3.863600,-2.643000,-6.609200,80051.000000,0.000000,203.000000,6.040064e+10,0.000000
25%,4.076870e+05,72.000000,2008.000000,66.800000,533.000000,2.000000,66.785000,533.000000,0.000000,2012.000000,...,-0.589900,-0.287100,-0.604800,-0.877800,-0.669200,83451.000000,6.000000,2603.500000,3.820527e+13,267.500000
50%,7.311070e+05,79.600000,2009.000000,74.600000,4450.000000,2.000000,72.000000,4450.000000,0.000000,2013.000000,...,0.128200,0.212400,0.163700,-0.234400,0.028400,86315.000000,48.000000,2690.000000,3.512258e+15,540.000000
75%,1.037145e+06,86.000000,2009.000000,82.800000,9020.000000,2.000000,76.190000,9020.000000,1.000000,2014.000000,...,0.702700,0.865100,0.778500,0.399500,0.541900,87568.000000,237.000000,2961.500000,4.610806e+15,817.000000
max,1.297877e+06,97.000000,2012.000000,98.200000,18409.000000,2.000000,99.000000,18409.000000,1.000000,2017.000000,...,1.995300,1.904800,2.161700,2.934900,1.630200,89894.000000,999.000000,9976.000000,4.994754e+18,9850.000000

In [13]:
# <fill_this>

validation_df.head()

,ID,Gender,DOB,10percentage,12graduation,12percentage,CollegeID,CollegeTier,Degree,Specialization,...,city,postcode,state_abbr,address,cc_number,cc_expiry,cc_security_code,company_name,company_suffix,user_agent
0,230553,m,1992-05-01,66.66,2005,80.4,64,2,B.Tech/B.E.,information technology,...,West Markfurt,2620,NSW,"Unit 45 94 Horton Square Quadrant, West Markfu...",2242932096939572,12/28,923,"Martinez, Escobar and Pearson",PLC,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_7_4...
1,1038837,m,1990-09-21,73.00,2008,76.0,10930,2,B.Tech/B.E.,information technology,...,Port Juliatown,2610,SA,"Apt. 716 09 Mike Spur Mew, Port Juliatown SA,...",6522535142244129,01/32,887,"Summers, Johnson and Cordova",PLC,Mozilla/5.0 (Windows; U; Windows 95) AppleWebK...
2,781196,m,1991-02-09,78.40,2009,58.4,11013,2,B.Tech/B.E.,automobile/automotive engineering,...,New Samuel,2934,NT,"Level 0 03 Richardson Bridge Part, New Samuel ...",4370495287115,12/24,3737,Delgado-Johnson,Group,Opera/9.76.(X11; Linux i686; tg-TJ) Presto/2.9...
3,661812,f,1991-09-23,71.00,2009,68.0,13040,2,B.Tech/B.E.,computer science & engineering,...,Walkerbury,912,WA,"8/21 Katherine Trunkway Avenue, Walkerbury WA...",4732797787775939,06/28,763,"Johnson, Hill and Huynh",Ltd,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.7.20) G...
4,657409,m,1992-01-08,76.50,2009,84.0,11447,2,B.Tech/B.E.,mechanical engineering,...,West Kennethbury,2968,NT,"Level 8 2 Hull Brace Siding, West Kennethbury ...",501848336365,11/30,76,"Mullen, Barnes and Norman",LLC,Mozilla/5.0 (compatible; MSIE 6.0; Windows NT ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594,309190,m,1986-02-06,48.00,2004,63.6,5904,2,B.Tech/B.E.,electronics and communication engineering,...,East Craigport,2680,TAS,"Level 1 1 Joel Centreway Plateau, East Craigpo...",4653961344289744,05/30,820,Austin-Brown,and Sons,Mozilla/5.0 (X11; Linux i686) AppleWebKit/531....
595,35122,m,1991-02-14,62.00,2006,71.0,374,2,B.Tech/B.E.,computer engineering,...,Morenoland,2129,SA,"Suite 703 141 Benjamin Alley Mount, Morenoland...",4518254033325515,11/30,52,"Sanchez, Dudley and Hampton",Ltd,Mozilla/5.0 (compatible; MSIE 6.0; Windows 95;...
596,568835,m,1991-01-07,77.20,2008,79.8,13594,1,B.Tech/B.E.,computer science & engineering,...,North Sarahfurt,2938,SA,"Unit 77 860 Flores Brace Thoroughfare, North S...",4486633672168522140,05/27,317,"Mckinney, Juarez and Duke",and Sons,Mozilla/5.0 (compatible; MSIE 6.0; Windows 98;...
597,295545,m,1987-11-17,73.73,2005,72.5,127,2,MCA,computer application,...,Jonathanmouth,2637,ACT,"Unit 48 9 Hancock Lees Reach, Jonathanmouth A...",4952913822613760,10/29,341,"Cole, Mcfarland and Mccoy",Ltd,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_3 like M...
598,326612,m,1990-09-15,87.60,2008,86.4,3879,2,B.Tech/B.E.,computer engineering,...,Kevinshire,6078,NT,"Flat 40 72 Fernandez Rosebowl Drive, Kevinshir...",2720185227966268,09/32,30,Blevins-Gay,and Sons,Opera/9.56.(Windows NT 11.0; en-ZA) Presto/2.9...

> Insights:

In [15]:
training_df.shape

(1803, 58)

In [16]:
validation_df.describe()

,ID,10percentage,12graduation,12percentage,CollegeID,CollegeTier,collegeGPA,CollegeCityID,CollegeCityTier,GraduationYear,...,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience,Salary,building_number,postcode,cc_number,cc_security_code
count,5.990000e+02,599.000000,599.000000,599.000000,599.000000,599.000000,599.000000,599.000000,599.000000,599.000000,...,599.000000,599.000000,599.000000,599.000000,599.000000,599.000000,599.000000,599.000000,5.990000e+02,599.000000
mean,6.915486e+05,74.281452,2007.896494,71.254808,5596.098497,1.969950,70.090668,5596.098497,0.288815,2012.587646,...,-0.074873,-0.014886,-0.086081,0.000839,-0.228156,81917.444073,172.904841,3146.682805,3.276011e+17,871.373957
std,3.776581e+05,10.236754,1.665900,11.195747,4903.705079,0.170868,8.202505,4903.705079,0.453590,1.369244,...,1.053137,1.093153,1.017807,1.054412,1.152604,4717.619817,264.677154,1774.104698,1.172907e+18,1535.834979
min,2.122900e+04,43.000000,2001.000000,43.000000,13.000000,1.000000,6.850000,13.000000,0.000000,2007.000000,...,-3.893300,-5.781600,-4.600900,-2.643000,-7.375700,76830.000000,0.000000,208.000000,6.044157e+10,5.000000
25%,3.305635e+05,67.000000,2007.000000,63.000000,993.000000,2.000000,65.000000,993.000000,0.000000,2012.000000,...,-0.733500,-0.453600,-0.706800,-0.741500,-0.761500,79156.000000,5.000000,2601.000000,1.800400e+14,268.000000
50%,6.609380e+05,75.000000,2008.000000,70.000000,4439.000000,2.000000,70.000000,4439.000000,0.000000,2013.000000,...,-0.015400,0.212400,0.010000,0.003530,-0.094300,80767.000000,39.000000,2713.000000,3.506287e+15,537.000000
75%,1.062176e+06,82.000000,2009.000000,79.800000,9459.000000,2.000000,75.180000,9459.000000,1.000000,2014.000000,...,0.702700,0.711900,0.599400,0.767300,0.480500,82020.000000,246.500000,2966.500000,4.618192e+15,801.000000
max,1.297763e+06,97.120000,2011.000000,97.500000,17782.000000,2.000000,96.700000,17782.000000,1.000000,2017.000000,...,1.995300,1.787800,2.161700,3.352500,1.630200,95621.000000,997.000000,9998.000000,4.995476e+18,9688.000000

In [ ]:
# <fill_this>

validation_df

,ID,Gender,DOB,10percentage,12graduation,12percentage,CollegeID,CollegeTier,Degree,Specialization,...,city,postcode,state_abbr,address,cc_number,cc_expiry,cc_security_code,company_name,company_suffix,user_agent
0,230553,m,1992-05-01,66.66,2005,80.4,64,2,B.Tech/B.E.,information technology,...,West Markfurt,2620,NSW,"Unit 45 94 Horton Square Quadrant, West Markfu...",2242932096939572,12/28,923,"Martinez, Escobar and Pearson",PLC,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_7_4...
1,1038837,m,1990-09-21,73.00,2008,76.0,10930,2,B.Tech/B.E.,information technology,...,Port Juliatown,2610,SA,"Apt. 716 09 Mike Spur Mew, Port Juliatown SA,...",6522535142244129,01/32,887,"Summers, Johnson and Cordova",PLC,Mozilla/5.0 (Windows; U; Windows 95) AppleWebK...
2,781196,m,1991-02-09,78.40,2009,58.4,11013,2,B.Tech/B.E.,automobile/automotive engineering,...,New Samuel,2934,NT,"Level 0 03 Richardson Bridge Part, New Samuel ...",4370495287115,12/24,3737,Delgado-Johnson,Group,Opera/9.76.(X11; Linux i686; tg-TJ) Presto/2.9...
3,661812,f,1991-09-23,71.00,2009,68.0,13040,2,B.Tech/B.E.,computer science & engineering,...,Walkerbury,912,WA,"8/21 Katherine Trunkway Avenue, Walkerbury WA...",4732797787775939,06/28,763,"Johnson, Hill and Huynh",Ltd,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.7.20) G...
4,657409,m,1992-01-08,76.50,2009,84.0,11447,2,B.Tech/B.E.,mechanical engineering,...,West Kennethbury,2968,NT,"Level 8 2 Hull Brace Siding, West Kennethbury ...",501848336365,11/30,76,"Mullen, Barnes and Norman",LLC,Mozilla/5.0 (compatible; MSIE 6.0; Windows NT ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594,309190,m,1986-02-06,48.00,2004,63.6,5904,2,B.Tech/B.E.,electronics and communication engineering,...,East Craigport,2680,TAS,"Level 1 1 Joel Centreway Plateau, East Craigpo...",4653961344289744,05/30,820,Austin-Brown,and Sons,Mozilla/5.0 (X11; Linux i686) AppleWebKit/531....
595,35122,m,1991-02-14,62.00,2006,71.0,374,2,B.Tech/B.E.,computer engineering,...,Morenoland,2129,SA,"Suite 703 141 Benjamin Alley Mount, Morenoland...",4518254033325515,11/30,52,"Sanchez, Dudley and Hampton",Ltd,Mozilla/5.0 (compatible; MSIE 6.0; Windows 95;...
596,568835,m,1991-01-07,77.20,2008,79.8,13594,1,B.Tech/B.E.,computer science & engineering,...,North Sarahfurt,2938,SA,"Unit 77 860 Flores Brace Thoroughfare, North S...",4486633672168522140,05/27,317,"Mckinney, Juarez and Duke",and Sons,Mozilla/5.0 (compatible; MSIE 6.0; Windows 98;...
597,295545,m,1987-11-17,73.73,2005,72.5,127,2,MCA,computer application,...,Jonathanmouth,2637,ACT,"Unit 48 9 Hancock Lees Reach, Jonathanmouth A...",4952913822613760,10/29,341,"Cole, Mcfarland and Mccoy",Ltd,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_3 like M...
598,326612,m,1990-09-15,87.60,2008,86.4,3879,2,B.Tech/B.E.,computer engineering,...,Kevinshire,6078,NT,"Flat 40 72 Fernandez Rosebowl Drive, Kevinshir...",2720185227966268,09/32,30,Blevins-Gay,and Sons,Opera/9.56.(Windows NT 11.0; en-ZA) Presto/2.9...

> Insights: <fill_this>

In [ ]:
# <fill_this>

testing_df

,ID,Gender,DOB,10percentage,12graduation,12percentage,CollegeID,CollegeTier,Degree,Specialization,...,city,postcode,state_abbr,address,cc_number,cc_expiry,cc_security_code,company_name,company_suffix,user_agent
0,669692,m,1992-05-04,73.00,2009,71.00,9699,2,B.Tech/B.E.,information technology,...,Port Jeremy,2932,TAS,"Apt. 722 439 Carla Rest Anchorage, Port Jeremy...",3574122070931458,07/29,940,Wilkerson-Drake,Group,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_7_0...
1,87319,m,1986-10-27,56.40,2006,72.00,403,2,B.Tech/B.E.,mechanical engineering,...,Allisonport,2945,NT,"Suite 032 9 Snyder Towers Mews, Allisonport N...",343309856836862,05/33,871,"Edwards, Ortiz and Jenkins",LLC,Mozilla/5.0 (Linux; Android 3.2.5) AppleWebKit...
2,962441,m,1992-08-10,88.67,2009,87.69,436,1,B.Tech/B.E.,chemical engineering,...,North Carrieton,2985,QLD,"Level 4 1 Salazar Parade Driveway, North Carri...",340365375460967,10/29,999,Wood-Smith,PLC,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_12_...
3,110863,m,1988-08-04,85.60,2006,90.60,964,2,B.Tech/B.E.,electronics and communication engineering,...,Anthonymouth,2933,QLD,"Unit 79 6 Sharon Right Of Way Vista, Anthonymo...",4253956772863789235,08/32,29,"Curtis, Hubbard and Benton",LLC,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_0 like M...
4,1083018,m,1992-08-25,91.00,2010,91.20,2921,2,B.Tech/B.E.,electronics and communication engineering,...,Gregoryville,2812,NSW,"Apt. 191 851 Robert Reserve Pocket, Gregoryvil...",3518469177981764,05/29,306,Peters-Brown,and Sons,Opera/9.59.(X11; Linux i686; de-LI) Presto/2.9...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591,910069,m,1993-05-07,89.00,2010,82.20,4042,2,B.Tech/B.E.,computer science & engineering,...,Dayborough,5960,SA,"4/33 Williams Entrance Landing, Dayborough SA...",6011812702430507,05/30,580,"Moore, Hill and Singleton",PLC,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9...
592,262440,m,1988-02-07,78.00,2006,83.00,8637,1,B.Tech/B.E.,computer engineering,...,Fishertown,7667,VIC,"Apt. 080 579 Powers Approach Mall, Fishertown ...",6519698035605502,06/27,2858,Young LLC,Ltd,Opera/8.63.(Windows NT 6.1; af-ZA) Presto/2.9....
593,337533,m,1990-09-18,90.30,2008,96.25,3076,2,B.Tech/B.E.,electronics and communication engineering,...,Lisafurt,2617,ACT,"Flat 15 7 Mejia Range Trail, Lisafurt ACT, 2617",4750206761081104726,11/29,558,"Smith, Brennan and Mills",PLC,Opera/9.61.(Windows NT 5.0; tig-ER) Presto/2.9...
594,896469,m,1992-05-29,86.88,2010,80.83,356,2,B.Tech/B.E.,computer science & engineering,...,Millerfurt,8836,SA,"810/110 Love Rise Crescent, Millerfurt SA, 8836",30107251768799,01/31,842,Jackson LLC,Ltd,Mozilla/5.0 (iPad; CPU iPad OS 14_2 like Mac O...
595,715228,m,1991-08-06,82.80,2008,73.11,2766,2,B.Tech/B.E.,electronics and communication engineering,...,St. Jeffery,2970,WA,"Suite 549 65 Brittany Nook Quadrant, St. Jeffe...",180011044749561,11/31,798,Freeman-Ruiz,Group,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...

> Insights: <fill_this>

In [ ]:
# <fill_this>

> Insights: <fill_this>

In [ ]:
# <fill_this>

> Insights: <fill_this>

> Considerations: <fill_this>

> Issues found: <fill_this>

<hr>

### C.3 Explore Target variable

In [ ]:
# Set the name of the target column
# <fill_this>

target_name = ''

In [ ]:
# <fill_this>

training_df[target_name]

> Insights: <fill_this>

In [ ]:
# <fill_this>

> Insights: <fill_this>

In [ ]:
# <fill_this>

> Insights: <fill_this>

> Considerations: <fill_this>

> Issues found: <fill_this>

<hr>

### C.4 Explore Variables of Interest

<hr>

#### C.4.a Feature "<put_name_here>"

In [ ]:
# <fill_this>

training_df['']

> Insights: <fill_this>

In [ ]:
# <fill_this>

> Insights: <fill_this>

In [ ]:
# <fill_this>

> Insights: <fill_this>

> Considerations: <fill_this>

> Issues found: <fill_this>

#### C.4.b Feature "<put_name_here>"

In [ ]:
# <fill_this>

training_df['']

> Insights: <fill_this>

In [ ]:
# <fill_this>

> Insights: <fill_this>

In [ ]:
# <fill_this>

> Insights: <fill_this>

> Considerations: <fill_this>

> Issues found: <fill_this>

<hr>

## D. Feature Selection

In [ ]:
feature_selection_executive_summary = '<fill_this>'

### D.1 Approach 1

> Rationale: <fill_this>

In [ ]:
# <fill_this>

> Results: <fill_this>

### D.2 Approach 2

> Rationale: <fill_this>

In [ ]:
# <fill_this>

> Results: <fill_this>

### D.3 Final Selection of Features

In [ ]:
# <fill_this>

features_list = []

<hr>

## E. Data Cleaning

In [ ]:
data_cleaning_executive_summary = '<fill_this>'

### E.1 Copy Datasets

In [ ]:
# Create copy of datasets
# Do not change this code

training_df_clean = training_df[features_list].copy()
validation_df_clean = validation_df[features_list].copy()
testing_df_clean = testing_df[features_list].copy()

<hr>

### E.2 Fixing "<put_issue_here>"

> Rationale: <fill_this>

In [ ]:
# <fill_this>

> Results: <fill_this>

<hr>

### E.3 Fixing "<put_issue_here>"

> Rationale: <fill_this>

In [ ]:
# <fill_this>

> Results: <fill_this>

<hr>

### E.4 Fixing "<put_issue_here>"

> Rationale:  <fill_this>

In [ ]:
# <fill_this>

> Results: <fill_this>

<hr>

## F. Feature Engineering

In [ ]:
feature_engineering_executive_summary = '<fill_this>'

<hr>

### F.1 Copy Datasets

In [ ]:
# Create copy of datasets
# Do not change this code

training_df_eng = training_df_clean.copy()
validation_df_eng = validation_df_clean.copy()
testing_df_eng = testing_df_clean.copy()

<hr>

### F.2 New Feature "<put_name_here>"

> Rationale: <fill_this>

In [ ]:
# <fill_this>

> Results: <fill_this>

<hr>

### F.3 New Feature "<put_name_here>"

> Rationale: <fill_this>

In [ ]:
# <fill_this>

> Results: <fill_this>

<hr>

### F.4 New Feature "<put_name_here>"

> Rationale: <fill_this>

In [ ]:
# <fill_this>

> Results: <fill_this>

<hr>

## G. Data Preparation for Modeling

In [ ]:
modeling_preparation_executive_summary = '<fill_this>'

<hr>

### G.1 Split Datasets

In [ ]:
# Create copy of datasets
# Do not change this code

X_train = training_df_eng.copy()
X_val = validation_df.copy()
X_test = testing_df.copy()

y_train = X_train.pop(target_name)
y_val = X_val.pop(target_name)
y_test = X_test.pop(target_name)

<hr>

### G.2 Data Transformation <put_name_here>

> Rationale: <fill_this>

In [ ]:
# <fill_this>

> Results: <fill_this>

<hr>

### G.3 Data Transformation <put_name_here>

> Rationale: <fill_this>

In [ ]:
# <fill_this>

> Results: <fill_this>

<hr>

### G.4 Data Transformation <put_name_here>

> Rationale: <fill_this>

In [ ]:
# <fill_this>

> Results: <fill_this>

<hr>

## H. Save Datasets

In [ ]:
# Save training set
# Do not change this code

X_train.to_csv('X_train.csv', index=False)
y_train.to_csv('y_train.csv', index=False)

In [ ]:
# Save validation set
# Do not change this code

X_val.to_csv('X_val.csv', index=False)
y_val.to_csv('y_val.csv', index=False)

In [ ]:
# Save testing set
# Do not change this code

X_test.to_csv('X_test.csv', index=False)
y_test.to_csv('y_test.csv', index=False)

## I. Assess Baseline Model

In [ ]:
baseline_model_executive_summary = '<fill_this>'

<hr>

### I.1 Simulate Predictions with Baseline Model

> Rationale: <fill_this>

In [ ]:
# Define central value for baseline model
# <fill_this>

y_central =

In [ ]:
# <fill_this>

training_preds =

<hr>

### I.2 Selection of Performance Metrics

> Rationale: <fill_this>

In [ ]:
# <fill_this>

from sklearn.metrics import

<hr>

### I.2 Baseline Model Performance

In [ ]:
# <fill_this>

> Results: <fill_this>

<hr>

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=737d9b25-9447-484d-8bc7-c0ef42078df9' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>